name: omnisci-connector-dev
channels:
- conda-forge
- defaults
dependencies:
- thrift=0.13.0
- python>3.6.6,<3.8
- sqlalchemy
- coverage
- numpy
- flake8
- black
- pre-commit
- pytest-cov
- pytest-mock
- requests
- sphinx
- sphinx_rtd_theme
